[theme]

# Primary accent for interactive elements
primaryColor = '#D9D9D9'

# Background color for the main content area
backgroundColor= '#B7C9F2'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor  = '#9195F6'

# Color used for almost all text
textColor = '#000'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"
